### ISSUE TITLE
Add development mode that watches for file changes and automatically builds them to the dist directory

### ISSUE THREAD

**Issue by alarner** [alarner/perk-cli#11]

**Comment by dhruvdutt** [comment]
@alarner Can I do it?

**Comment by alarner** [comment]
@dhruvdutt absolutely! I use chokidar to watch for changes on the [perk server](https://github.com/alarner/perk/blob/master/build/server.js#L60) so that could work, but I'm open to other suggestions. Maybe nodemon instead?

**Comment by dhruvdutt** [comment]
How about gulp?

**Comment by alarner** [comment]
Sure, that works too

**Comment by dhruvdutt** [comment]
#14 @alarner

**Comment by alarner** [comment]
Fixed in #14
