### ISSUE TITLE
Add link in readme to the perk slack team for help

### ISSUE THREAD

**Issue by alarner** [alarner/perk-cli#12]
https://docs.google.com/forms/d/e/1FAIpQLSeKAZfd_H0fyYTEr_cbrhK1RTWgn0cBr0iRdc2WEZ89WgFCCg/viewform?c=0&w=1

**Comment by mohitbhatia1994** [comment]
I will do it.

**Comment by alarner** [comment]
@mohitbhatia1994 it looks like @samit4me already did in #13, but there's a similar one [here](https://github.com/alarner/perk-docs/issues/45)

**Comment by ramswaroop** [comment]
https://github.com/alarner/perk-docs/pull/46

**Comment by samit4me** [comment]
Not sure where my name came from @alarner ???

**Comment by mohitbhatia1994** [comment]
@samit4me you should keep in mind to comment that you have claimed the issue. It will be a great help.

**Comment by samit4me** [comment]
@alarner @mohitbhatia1994 I do not know what is going on here, but I've made no claims or PRs, the PR was made by @ramswaroop . How did my name get thrown into this issue?

**Comment by alarner** [comment]
@samit4me I apologize, I must have typed in the wrong name. My mistake!

**Comment by mohitbhatia1994** [comment]
@ramswaroop you should keep in mind to comment that you have claimed the issue. It will be a great help.

**Comment by ramswaroop** [comment]
@mohitbhatia1994 Agree. New to hacktoberfest. 

But this issue was a very small one, took me the same time to do it as it would take me to comment here. :)
